#pragma once

//#include "storm-figaro/figaro/BDMP_23_Two_proc_comp_sys/No_Trim_No_Repair/FigaroModelBDMP_23_Two_proc_comp_sys_No_Trim_No_Repair.h"
//#include "storm-figaro/figaro/BDMP_23_Two_proc_comp_sys/Trim_Max_Repair/FigaroModelBDMP_23_Two_proc_comp_sys_Trim_Max_Repair.h"
//#include "storm-figaro/figaro/BDMP_23_Two_proc_comp_sys/Trim_article_Repair/FigaroModelBDMP_23_Two_proc_comp_sys_Trim_article_Repair.h"
//#include "storm-figaro/figaro/BDMP_23_Two_proc_comp_sys/Trim_Max_No_Repair/FigaroModelBDMP_23_Two_proc_comp_sys_Trim_Max_No_Repair.h"
//#include "storm-figaro/figaro/BDMP_23_Two_proc_comp_sys/No_Trim_Repair/FigaroModelBDMP_23_Two_proc_comp_sys_No_Trim_Repair.h"
//#include "storm-figaro/figaro/BDMP_23_Two_proc_comp_sys/Trim_article_No_Repair/FigaroModelBDMP_23_Two_proc_comp_sys_Trim_article_No_Repair.h"
//#include "storm-figaro/figaro/BDMP_04_Demoeng/No_trim_No_repair/FigaroModelBDMP_04_Demoeng_No_trim_No_repair.h"
//#include "storm-figaro/figaro/BDMP_04_Demoeng/Trim_Max_repair/FigaroModelBDMP_04_Demoeng_Trim_Max_repair.h"
//#include "storm-figaro/figaro/BDMP_04_Demoeng/Trim_Article_repair/FigaroModelBDMP_04_Demoeng_Trim_Article_repair.h"
//#include "storm-figaro/figaro/BDMP_04_Demoeng/Trim_Max_No_repair/FigaroModelBDMP_04_Demoeng_Trim_Max_No_repair.h"
//#include "storm-figaro/figaro/BDMP_04_Demoeng/No_trim_repair/FigaroModelBDMP_04_Demoeng_No_trim_repair.h"
//#include "storm-figaro/figaro/BDMP_04_Demoeng/Trim_Article_No_repair/FigaroModelBDMP_04_Demoeng_Trim_Article_No_repair.h"
//#include "storm-figaro/figaro/BDMP_13_Share1/No_trim_No_repair/FigaroModelBDMP_13_Share1_No_trim_No_repair.h"
//#include "storm-figaro/figaro/BDMP_13_Share1/Trim_Max_repair/FigaroModelBDMP_13_Share1_Trim_Max_repair.h"
//#include "storm-figaro/figaro/BDMP_13_Share1/Trim_Article_repair/FigaroModelBDMP_13_Share1_Trim_Article_repair.h"
//#include "storm-figaro/figaro/BDMP_13_Share1/Trim_Max_No_repair/FigaroModelBDMP_13_Share1_Trim_Max_No_repair.h"
//#include "storm-figaro/figaro/BDMP_13_Share1/No_trim_repair/FigaroModelBDMP_13_Share1_No_trim_repair.h"
//#include "storm-figaro/figaro/BDMP_13_Share1/Trim_Article_No_repair/FigaroModelBDMP_13_Share1_Trim_Article_No_repair.h"
//#include "storm-figaro/figaro/BDMP_18_ESREL_2013_Event_trees_and_Petri_nets/No_trim_No_repair/FigaroModelBDMP_18_ESREL_2013_Event_trees_and_Petri_nets_No_trim_No_repair.h"
//#include "storm-figaro/figaro/BDMP_18_ESREL_2013_Event_trees_and_Petri_nets/Trim_Max_No_repair/FigaroModelBDMP_18_ESREL_2013_Event_trees_and_Petri_nets_Trim_Max_No_repair.h"
//#include "storm-figaro/figaro/BDMP_18_ESREL_2013_Event_trees_and_Petri_nets/Trim_Article_No_repair/FigaroModelBDMP_18_ESREL_2013_Event_trees_and_Petri_nets_Trim_Article_No_repair.h"
//#include "storm-figaro/figaro/Petrinet/FigaroModelfigaro_Petrinet.h"
//#include "storm-figaro/figaro/BDMP_10_Project_risks/No_trim_No_repair/FigaroModelBDMP_10_Project_risks_No_trim_No_repair.h"
//#include "storm-figaro/figaro/BDMP_10_Project_risks/Trim_Max_repair/FigaroModelBDMP_10_Project_risks_Trim_Max_repair.h"
//#include "storm-figaro/figaro/BDMP_10_Project_risks/Trim_Article_repair/FigaroModelBDMP_10_Project_risks_Trim_Article_repair.h"
//#include "storm-figaro/figaro/BDMP_10_Project_risks/Trim_Max_No_repair/FigaroModelBDMP_10_Project_risks_Trim_Max_No_repair.h"
//#include "storm-figaro/figaro/BDMP_10_Project_risks/No_trim_repair/FigaroModelBDMP_10_Project_risks_No_trim_repair.h"
//#include "storm-figaro/figaro/BDMP_10_Project_risks/Trim_Article_No_repair/FigaroModelBDMP_10_Project_risks_Trim_Article_No_repair.h"
//#include "storm-figaro/figaro/BDMP_05/No_trim_No_repair/FigaroModelBDMP_05_No_trim_No_repair.h"
//#include "storm-figaro/figaro/BDMP_05/Trim_Max_repair/FigaroModelBDMP_05_Trim_Max_repair.h"
//#include "storm-figaro/figaro/BDMP_05/Trim_Article_repair/FigaroModelBDMP_05_Trim_Article_repair.h"
//#include "storm-figaro/figaro/BDMP_05/Trim_Max_No_repair/FigaroModelBDMP_05_Trim_Max_No_repair.h"
//#include "storm-figaro/figaro/BDMP_05/No_trim_repair/FigaroModelBDMP_05_No_trim_repair.h"
//#include "storm-figaro/figaro/BDMP_05/Trim_Article_No_repair/FigaroModelBDMP_05_Trim_Article_No_repair.h"
//#include "storm-figaro/figaro/BDMP/FigaroModelfigaro_BDMP.h"
//#include "storm-figaro/figaro/Telecom/FigaroModelfigaro_Telecom.h"
//#include "storm-figaro/figaro/BDMP_21_Remote_Access_Server_Security/No_trim_No_repair/FigaroModelBDMP_21_Remote_Access_Server_Security_No_trim_No_repair.h"
//#include "storm-figaro/figaro/BDMP_21_Remote_Access_Server_Security/Trim_Max_No_repair/FigaroModelBDMP_21_Remote_Access_Server_Security_Trim_Max_No_repair.h"
//#include "storm-figaro/figaro/BDMP_21_Remote_Access_Server_Security/Trim_Article_No_repair/FigaroModelBDMP_21_Remote_Access_Server_Security_Trim_Article_No_repair.h"
//#include "storm-figaro/figaro/BDMP_03_CCF/No_Trim_No_repair/FigaroModelBDMP_03_CCF_No_Trim_No_repair.h"
//#include "storm-figaro/figaro/BDMP_03_CCF/Trim_Max_repair/FigaroModelBDMP_03_CCF_Trim_Max_repair.h"
//#include "storm-figaro/figaro/BDMP_03_CCF/Trim_Article_repair/FigaroModelBDMP_03_CCF_Trim_Article_repair.h"
//#include "storm-figaro/figaro/BDMP_03_CCF/Trim_Max_No_repair/FigaroModelBDMP_03_CCF_Trim_Max_No_repair.h"
//#include "storm-figaro/figaro/BDMP_03_CCF/No_Trim_repair/FigaroModelBDMP_03_CCF_No_Trim_repair.h"
//#include "storm-figaro/figaro/BDMP_03_CCF/Trim_Article_No_repair/FigaroModelBDMP_03_CCF_Trim_Article_No_repair.h"
//#include "storm-figaro/figaro/RBD/FigaroModelfigaro_RBD.h"
//#include "storm-figaro/figaro/BDMP_01_2trainsElec/No_trim_No_repair/FigaroModelBDMP_01_2trainsElec_No_trim_No_repair.h"
//#include "storm-figaro/figaro/BDMP_01_2trainsElec/Trim_Max_repair/FigaroModelBDMP_01_2trainsElec_Trim_Max_repair.h"
//#include "storm-figaro/figaro/BDMP_01_2trainsElec/Trim_Article_repair/FigaroModelBDMP_01_2trainsElec_Trim_Article_repair.h"
//#include "storm-figaro/figaro/BDMP_01_2trainsElec/Trim_Max_No_repair/FigaroModelBDMP_01_2trainsElec_Trim_Max_No_repair.h"
//#include "storm-figaro/figaro/BDMP_01_2trainsElec/No_trim_repair/FigaroModelBDMP_01_2trainsElec_No_trim_repair.h"
//#include "storm-figaro/figaro/BDMP_01_2trainsElec/Trim_Article_No_repair/FigaroModelBDMP_01_2trainsElec_Trim_Article_No_repair.h"
//#include "storm-figaro/figaro/BDMP_02_3trains_standby_redundancy/No_trim_No_repair/FigaroModelBDMP_02_3trains_standby_redundancy_No_trim_No_repair.h"
//#include "storm-figaro/figaro/BDMP_02_3trains_standby_redundancy/Trim_Max_repair/FigaroModelBDMP_02_3trains_standby_redundancy_Trim_Max_repair.h"
//#include "storm-figaro/figaro/BDMP_02_3trains_standby_redundancy/Trim_Article_repair/FigaroModelBDMP_02_3trains_standby_redundancy_Trim_Article_repair.h"
//#include "storm-figaro/figaro/BDMP_02_3trains_standby_redundancy/Trim_Max_No_repair/FigaroModelBDMP_02_3trains_standby_redundancy_Trim_Max_No_repair.h"
//#include "storm-figaro/figaro/BDMP_02_3trains_standby_redundancy/No_trim_repair/FigaroModelBDMP_02_3trains_standby_redundancy_No_trim_repair.h"
//#include "storm-figaro/figaro/BDMP_02_3trains_standby_redundancy/Trim_Article_No_repair/FigaroModelBDMP_02_3trains_standby_redundancy_Trim_Article_No_repair.h"
//#include "storm-figaro/figaro/Miniplant/FigaroModelfigaro_Miniplant.h"
//#include "storm-figaro/figaro/BDMP_08_PC/No_trim_No_repair/FigaroModelBDMP_08_PC_No_trim_No_repair.h"
//#include "storm-figaro/figaro/BDMP_08_PC/Trim_Max_repair/FigaroModelBDMP_08_PC_Trim_Max_repair.h"
//#include "storm-figaro/figaro/BDMP_08_PC/Trim_Article_repair/FigaroModelBDMP_08_PC_Trim_Article_repair.h"
//#include "storm-figaro/figaro/BDMP_08_PC/Trim_Max_No_repair/FigaroModelBDMP_08_PC_Trim_Max_No_repair.h"
//#include "storm-figaro/figaro/BDMP_08_PC/No_trim_repair/FigaroModelBDMP_08_PC_No_trim_repair.h"
//#include "storm-figaro/figaro/BDMP_08_PC/Trim_Article_No_repair/FigaroModelBDMP_08_PC_Trim_Article_No_repair.h"
//
//#include "storm-figaro/figaro/BenchmarksEDF2017/6_6kV_Electrical_supply/FigaroModelBenchmarksEDF2017_6_6kV_Electrical_supply.h"
//#include "storm-figaro/figaro/BenchmarksEDF2017/Telecom/FigaroModelBenchmarksEDF2017_Telecom.h"
//
//
//#include "storm-figaro/figaro/FFORT_Benchmarks/DuelProcessorReactorRegulation/FigaroModelFFORT_Benchmarks_DuelProcessorReactorRegulation.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/RailwayCabinet/FigaroModelFFORT_Benchmarks_RailwayCabinet.h"
//
//#include "storm-figaro/figaro/FFORT_Benchmarks/RailwayCrossing/rc_10_1_sc_manually_written/FigaroModelRailwayCrossing_rc_10_1_sc_manually_written.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/RailwayCrossing/rc_30_1_sc/FigaroModelRailwayCrossing_rc_30_1_sc.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/RailwayCrossing/rc_30_30_sc/FigaroModelRailwayCrossing_rc_30_30_sc.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/SensorFilter/sf_8_2_manualy_written/FigaroModelSensorFilter_sf_8_2_manualy_written.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/SensorFilter/sf_9_6/FigaroModelSensorFilter_sf_9_6.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/TankFilling/FigaroModelFFORT_Benchmarks_TankFilling.h"
//#include "storm-figaro/figaro/RailwayStation/stationA_alternative/No_Trim_repair/FigaroModelstationA_alternative_No_Trim_repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/RailwayStation/stationH_alternative/No_Trim_repair/FigaroModelstationH_alternative_No_Trim_repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/RailwayStation/stationM_alternative/No_Trim_repair/FigaroModelstationM_alternative_No_Trim_repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/RailwayStation/stationA_standard/No_Trim_Repair/FigaroModelstationA_standard_No_Trim_Repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/RailwayStation/stationH_standard/No_Trim_Repair/FigaroModelstationH_standard_No_Trim_Repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/RailwayStation/stationM_standard/No_Trim_Repair/FigaroModelstationM_standard_No_Trim_Repair.h"
//
//#include "storm-figaro/figaro/FFORT_Benchmarks/VehicleGuidance/vgs_1/No_Trim_Repair/FigaroModelvgs_1_No_Trim_Repair.h"
//
//#include "storm-figaro/figaro/FFORT_Benchmarks/VehicleGuidance/vgs_1/Trim_repair/FigaroModelvgs_1_Trim_repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/VehicleGuidance/vgs_1/Trim_No_Repair/FigaroModelvgs_1_Trim_No_Repair.h"
//
//#include "storm-figaro/figaro/FFORT_Benchmarks/VehicleGuidance/vgs_2/No_Trim_Repair/FigaroModelvgs_2_No_Trim_Repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/VehicleGuidance/vgs_3/No_Trim_Repair/FigaroModelvgs_3_No_Trim_Repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/VehicleGuidance/vgs_4/No_Trim_Repair/FigaroModelvgs_4_No_Trim_Repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/VehicleGuidance/vgs_5/No_Trim_Repair/FigaroModelvgs_5_No_Trim_Repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/VehicleGuidance/vgs_6/No_Trim_Repair/FigaroModelvgs_6_No_Trim_Repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/VehicleGuidance/vgs_7/No_Trim_Repair/FigaroModelvgs_7_No_Trim_Repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/VehicleGuidance/vgs_8/No_Trim_Repair/FigaroModelvgs_8_No_Trim_Repair.h"
//
//
//#include "storm-figaro/figaro/FFORT_Benchmarks/Telecom/FigaroModelFFORT_Benchmarks_Telecom.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/Telecom/reduced/FigaroModelTelecom_reduced.h"

//
//#include "storm-figaro/figaro/FFORT_Benchmarks/NPPS/Trim_repair/FigaroModelNPPS_Trim_repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/NPPS/No_trim_No_repair/FigaroModelNPPS_No_trim_No_repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/NPPS/Trim_No_repair/FigaroModelNPPS_Trim_No_repair.h"
//#include "storm-figaro/figaro/NPPS/Trim_article_repair/FigaroModelNPPS_Trim_article_repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/NPPS/No_trim_repair/FigaroModelNPPS_No_trim_repair.h"
//#include "storm-figaro/figaro/NPPS/Trim_article_No_repair/FigaroModelNPPS_Trim_article_No_repair.h"

//#include "storm-figaro/figaro/FFORT_Benchmarks/statespacegeneation/sf4_2/trim_repair/FigaroModelsf4_2_trim_repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/statespacegeneation/sf4_2/trim_no_repair/FigaroModelsf4_2_trim_no_repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/statespacegeneation/sf3_2/trim_repair/FigaroModelsf3_2_trim_repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/statespacegeneation/sf3_2/trim_no_repair/FigaroModelsf3_2_trim_no_repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/statespacegeneation/sf2_2/trim_article_no_rep/FigaroModelsf2_2_trim_article_no_rep.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/statespacegeneation/sf2_2/trim_article_repair/FigaroModelsf2_2_trim_article_repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/statespacegeneation/sf5_2/trim_repair/FigaroModelsf5_2_trim_repair.h"
//#include "storm-figaro/figaro/FFORT_Benchmarks/statespacegeneation/sf5_2/trim_no_repair/FigaroModelsf5_2_trim_no_repair.h"

//#include "storm-figaro/figaro/Petrinet/FigaroModelfigaro_Petrinet.h"
//#include "storm-figaro/figaro/BDMP/nonrepairable/FigaroModelBDMP_nonrepairable.h"
//#include "storm-figaro/figaro/BDMP/repariable/FigaroModelBDMP_repariable.h"
//#include "storm-figaro/figaro/Telecom/FigaroModelfigaro_Telecom.h"
//#include "storm-figaro/figaro/RBD/FigaroModelfigaro_RBD.h"
//#include "storm-figaro/figaro/Miniplant/repairable/FigaroModelMiniplant_repairable.h"


//#include "storm-figaro/figaro/RailwayStation/stationA_alternative/Trim_Article_repair/FigaroModelstationA_alternative_Trim_Article_repair.h"
//#include "storm-figaro/figaro/RailwayStation/stationA_alternative/Trim_Article_No_repair/FigaroModelstationA_alternative_Trim_Article_No_repair.h"

/******Start RDFT test&**************/

//#include "storm-figaro/figaro/08_and_and_trig_common/FigaroModelfigaro_08_and_and_trig_common.h"
//#include "storm-figaro/figaro/06_or_trig/FigaroModelfigaro_06_or_trig.h"
//#include "storm-figaro/figaro/01_and/FigaroModelfigaro_01_and.h"
//#include "storm-figaro/figaro/03_and3/FigaroModelfigaro_03_and3.h"
//#include "storm-figaro/figaro/07_and_and_trig/FigaroModelfigaro_07_and_and_trig.h"
//#include "storm-figaro/figaro/11_inst_and/FigaroModelfigaro_11_inst_and.h"
//#include "storm-figaro/figaro/04_and_or/FigaroModelfigaro_04_and_or.h"
//#include "storm-figaro/figaro/02_or/FigaroModelfigaro_02_or.h"
//#include "storm-figaro/figaro/05_and_trig/FigaroModelfigaro_05_and_trig.h"
//#include "storm-figaro/figaro/09_and_inv_trig/FigaroModelfigaro_09_and_inv_trig.h"
//#include "storm-figaro/figaro/10_vot/FigaroModelfigaro_10_vot.h"
//#include "storm-figaro/figaro/12_test/FigaroModelfigaro_12_test.h"
//#include "storm-figaro/figaro/16_PAND_rep_last/FigaroModelfigaro_16_PAND_rep_last.h"
//#include "storm-figaro/figaro/15_PAND_rep_first/FigaroModelfigaro_15_PAND_rep_first.h"
//#include "storm-figaro/figaro/13_PAND_rep_all/FigaroModelfigaro_13_PAND_rep_all.h"
//#include "storm-figaro/figaro/14_PAND_rep_any/FigaroModelfigaro_14_PAND_rep_any.h"
//
//#include "storm-figaro/figaro/17_01/FigaroModelfigaro_17_01.h"
//#include "storm-figaro/figaro/17_02/FigaroModelfigaro_17_02.h"
//#include "storm-figaro/figaro/17_03/FigaroModelfigaro_17_03.h"
//#include "storm-figaro/figaro/17_04/FigaroModelfigaro_17_04.h"
//#include "storm-figaro/figaro/17_05/FigaroModelfigaro_17_05.h"
//#include "storm-figaro/figaro/17_06/FigaroModelfigaro_17_06.h"
//#include "storm-figaro/figaro/17_07/FigaroModelfigaro_17_07.h"
//#include "storm-figaro/figaro/17_08/FigaroModelfigaro_17_08.h"
//#include "storm-figaro/figaro/17_09/FigaroModelfigaro_17_09.h"
//#include "storm-figaro/figaro/17_10/FigaroModelfigaro_17_10.h"
//#include "storm-figaro/figaro/17_11/FigaroModelfigaro_17_11.h"
//#include "storm-figaro/figaro/17_12/FigaroModelfigaro_17_12.h"
//#include "storm-figaro/figaro/17_13/FigaroModelfigaro_17_13.h"
//#include "storm-figaro/figaro/17_14/FigaroModelfigaro_17_14.h"
//#include "storm-figaro/figaro/17_15/FigaroModelfigaro_17_15.h"
//
//#include "storm-figaro/figaro/17_16/FigaroModelfigaro_17_16.h"
//#include "storm-figaro/figaro/17_17/FigaroModelfigaro_17_17.h"
//#include "storm-figaro/figaro/17_18/FigaroModelfigaro_17_18.h"
//#include "storm-figaro/figaro/17_19/FigaroModelfigaro_17_19.h"
//#include "storm-figaro/figaro/17_20/FigaroModelfigaro_17_20.h"
//#include "storm-figaro/figaro/17_21/FigaroModelfigaro_17_21.h"
//#include "storm-figaro/figaro/17_22/FigaroModelfigaro_17_22.h"
//#include "storm-figaro/figaro/17_23/FigaroModelfigaro_17_23.h"
//#include "storm-figaro/figaro/17_23_A/FigaroModelfigaro_17_23_A.h"
//#include "storm-figaro/figaro/17_23_B/FigaroModelfigaro_17_23_B.h"
//#include "storm-figaro/figaro/04_A/FigaroModelfigaro_04_A.h"
//#include "storm-figaro/figaro/04_B/FigaroModelfigaro_04_B.h"
//#include "storm-figaro/figaro/17_24/FigaroModelfigaro_17_24.h"
//#include "storm-figaro/figaro/17_25/FigaroModelfigaro_17_25.h"
//#include "storm-figaro/figaro/17_26/FigaroModelfigaro_17_26.h"
//#include "storm-figaro/figaro/17_27/FigaroModelfigaro_17_27.h"
//#include "storm-figaro/figaro/17_28/FigaroModelfigaro_17_28.h"
//#include "storm-figaro/figaro/17_29/FigaroModelfigaro_17_29.h"
//#include "storm-figaro/figaro/17_30/FigaroModelfigaro_17_30.h"
//#include "storm-figaro/figaro/17_30/FigaroModelfigaro_17_30.h"
//#include "storm-figaro/figaro/17_31/FigaroModelfigaro_17_31.h"
//#include "storm-figaro/figaro/17_32/FigaroModelfigaro_17_32.h"
//#include "storm-figaro/figaro/17_33/FigaroModelfigaro_17_33.h"
//#include "storm-figaro/figaro/17_34/FigaroModelfigaro_17_34.h"
//#include "storm-figaro/figaro/17_35/FigaroModelfigaro_17_35.h"
//#include "storm-figaro/figaro/17_36/FigaroModelfigaro_17_36.h"
//#include "storm-figaro/figaro/17_37/FigaroModelfigaro_17_37.h"
//#include "storm-figaro/figaro/17_38/FigaroModelfigaro_17_38.h"
//#include "storm-figaro/figaro/17_39/FigaroModelfigaro_17_39.h"
//#include "storm-figaro/figaro/17_40/FigaroModelfigaro_17_40.h"
