//
// Created by Shahid Khan on 19.08.21.
//

#ifndef STORM_FIGAROSYMMETRYINFORMATIONPARSER_H
#define STORM_FIGAROSYMMETRYINFORMATIONPARSER_H


class FigaroSymmetryInformationParser {

};


#endif //STORM_FIGAROSYMMETRYINFORMATIONPARSER_H
